Repository apache/shardingsphere-elasticjob-ui, pull requests merged in 2021-07, with the labels that each got.

#118 Event trace history records order by date desc
  shardingsphere-elasticjob-lite-ui/shardingsphere-elasticjob-lite-ui-backend/src/main/java/org/apache/shardingsphere/elasticjob/lite/ui/service/impl/EventTraceHistoryServiceImpl.java
Labels: enhancement, tracing

#119 Update frontend-maven-plugin to 1.12.0
  pom.xml
Labels: dependencies

#120 Update ElasticJob dependencies to 3.0.0
  pom.xml
  shardingsphere-elasticjob-lite-ui/shardingsphere-elasticjob-lite-ui-backend/src/main/java/org/apache/shardingsphere/elasticjob/lite/ui/service/impl/JobAPIServiceImpl.java
Labels: dependencies

#121 Update release notes for 3.0.0
  RELEASE-NOTES.md
Labels: release

#122 Update release notes for 3.0.0
  RELEASE-NOTES.md
Labels: release

#124 Update NOTICE files
  NOTICE
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-cloud-ui-bin-distribution/src/main/release-docs/NOTICE
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-lite-ui-bin-distribution/src/main/release-docs/NOTICE
Labels: release

#128 3.0.0 release
  pom.xml
  shardingsphere-elasticjob-cloud-ui/pom.xml
  shardingsphere-elasticjob-cloud-ui/shardingsphere-elasticjob-cloud-ui-backend/pom.xml
  shardingsphere-elasticjob-cloud-ui/shardingsphere-elasticjob-cloud-ui-frontend/pom.xml
  shardingsphere-elasticjob-lite-ui/pom.xml
  shardingsphere-elasticjob-lite-ui/shardingsphere-elasticjob-lite-ui-backend/pom.xml
  shardingsphere-elasticjob-lite-ui/shardingsphere-elasticjob-lite-ui-frontend/pom.xml
  shardingsphere-elasticjob-ui-distribution/pom.xml
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-cloud-ui-bin-distribution/pom.xml
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-lite-ui-bin-distribution/pom.xml
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-ui-src-distribution/pom.xml
Labels: release

#127 support jdk11
  pom.xml
  shardingsphere-elasticjob-cloud-ui/shardingsphere-elasticjob-cloud-ui-backend/pom.xml
  shardingsphere-elasticjob-lite-ui/shardingsphere-elasticjob-lite-ui-backend/pom.xml
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-cloud-ui-bin-distribution/src/main/release-docs/LICENSE
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-cloud-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-jaxb.txt
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-lite-ui-bin-distribution/src/main/release-docs/LICENSE
  shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-lite-ui-bin-distribution/src/main/release-docs/licenses/LICENSE-jaxb.txt
Labels: build, dependencies
